export const projects = [
  {
    id: "sassyblend",
    index: "01",
    icon: "🛍️",
    status: "complete",
    type: "Full-Stack · E-Commerce",
    category: "Full-Stack",
    title: "SassyBlend Platform",
    tagline: "Production-grade MERN e-commerce & admin ecosystem",
    description:
      "A full-scale food/restaurant e-commerce platform with a companion admin dashboard. Covers the entire order lifecycle from cart to payment confirmation, with real-time notifications, coupon management, user security auditing, and a revenue analytics pipeline. Engineered solo from schema design to deployment.",
    longDescription:
      "Built with financial integrity as the primary constraint — every payment flow is triple-verified through Paystack webhooks with HMAC signature validation. The cart system uses MongoDB atomic operations to prevent race conditions under concurrent load. The admin panel wires together eight dashboard sections with animated sidebar navigation, global search, and cross-panel Redux state.",
    tags: [
      "Node.js",
      "Express",
      "MongoDB",
      "React",
      "Redux Toolkit",
      "Socket.io",
      "Paystack",
      "Cloudinary",
      "Resend",
      "Chakra UI",
      "Framer Motion",
      "Zod",
    ],
    chips: [
      { label: "Solo Build", variant: "y" },
      { label: "Full-Stack", variant: "b" },
      { label: "Production-Ready", variant: "o" },
    ],
    metrics: [
      { label: "Response Time", value: "<100ms" },
      { label: "Ghost Orders", value: "Zero" },
      { label: "Admin Sections", value: "8" },
    ],
    highlights: [
      "Triple-verified Paystack payment pipeline",
      "Atomic MongoDB ops for cart race conditions",
      "Cursor-based pagination for chat & products",
      "HMAC webhook verification on all events",
      "Centralised Zod validation middleware layer",
      "Redis & BullMQ extraction-ready architecture",
    ],
    links: [
      { label: "Case Study", href: "/case-studies/sassyblend-api" },
      { label: "GitHub", href: "#" },
    ],
    image: {
      aspect: "16/9",
      label: "Platform Overview",
      hint: "1200 × 675px recommended",
      accent: 0,
    },
  },
  {
    id: "chatspace",
    index: "02",
    icon: "💬",
    status: "live",
    type: "Real-Time · Backend",
    category: "Backend",
    title: "ChatSpace",
    tagline: "Real-time messaging with persistent history",
    description:
      "A real-time messaging platform with private DMs, group rooms, and read receipts. Features JWT authentication, persistent chat history with cursor-based pagination, and Socket.io rooms — designed to scale horizontally with a Redis adapter when needed.",
    longDescription:
      "The architecture separates the REST foundation from the Socket.io layer, allowing the chat history to be served from MongoDB with full pagination even when real-time is unavailable. Connection management is handled per-room with graceful reconnection logic. The cursor pagination strategy was chosen explicitly to avoid the offset degradation problem at large message volumes.",
    tags: [
      "React",
      "Express",
      "Socket.io",
      "MongoDB",
      "JWT",
      "Cursor Pagination",
      "Redis-ready",
    ],
    chips: [
      { label: "Live", variant: "y" },
      { label: "Real-Time", variant: "b" },
    ],
    metrics: [
      { label: "Latency", value: "<50ms" },
      { label: "Pagination", value: "Cursor" },
      { label: "Auth", value: "JWT" },
    ],
    highlights: [
      "Socket.io rooms with graceful reconnection",
      "Cursor-based message history pagination",
      "Hybrid REST + WebSocket architecture",
      "Redis adapter extraction path documented",
    ],
    links: [
      { label: "GitHub", href: "#" },
      { label: "Live Demo", href: "#" },
    ],
    image: {
      aspect: "16/9",
      label: "Chat Interface",
      hint: "1200 × 675px recommended",
      accent: 1,
    },
  },
  {
    id: "taskflow",
    index: "03",
    icon: "🗒️",
    status: "complete",
    type: "Full-Stack · Productivity",
    category: "Full-Stack",
    title: "TaskFlow",
    tagline: "Collaborative task boards with real-time updates",
    description:
      "A productivity app with real-time task boards, team collaboration, and deadline tracking. Built with drag-and-drop reordering, role-based access control, and optimistic UI updates throughout.",
    longDescription:
      "Role-based access control is enforced at both the route middleware level and the frontend component level — ensuring data visibility rules are consistent across the stack. Optimistic UI updates give instant feedback on drag operations while the server confirms the new sort order asynchronously. Deadline tracking uses server-side scheduled checks with in-app notification delivery.",
    tags: ["React", "Node.js", "MongoDB", "Socket.io", "RBAC", "Drag-and-Drop"],
    chips: [
      { label: "Complete", variant: "p" },
      { label: "Full-Stack", variant: "b" },
    ],
    metrics: [
      { label: "Auth Model", value: "RBAC" },
      { label: "UI Updates", value: "Optimistic" },
      { label: "Real-Time", value: "Socket.io" },
    ],
    highlights: [
      "Drag-and-drop with optimistic reorder",
      "Role-based access at route & UI level",
      "Server-side deadline notification system",
      "Real-time board sync across collaborators",
    ],
    links: [
      { label: "GitHub", href: "#" },
      { label: "Live Demo", href: "#" },
    ],
    image: {
      aspect: "16/9",
      label: "Task Board UI",
      hint: "1200 × 675px recommended",
      accent: 2,
    },
  },
  {
    id: "metrichub",
    index: "04",
    icon: "📊",
    status: "complete",
    type: "Analytics · Dashboard",
    category: "Frontend",
    title: "MetricHub",
    tagline: "Business analytics with pre-computed KPI pipelines",
    description:
      "A business analytics dashboard aggregating sales, traffic, and user data into visual charts. Includes date-range filtering, CSV export, and a MongoDB aggregation pipeline for pre-computed KPIs.",
    longDescription:
      "The aggregation strategy pre-computes KPIs at write time rather than read time — following the same principle behind materialised views and CQRS read-model projections. Date-range filters are pushed all the way through the Redux thunk to the MongoDB pipeline, not dropped silently mid-stack. CSV export streams directly from the aggregation result without intermediate buffering.",
    tags: [
      "React",
      "Recharts",
      "Node.js",
      "MongoDB Aggregation",
      "CSV Export",
      "Redux Toolkit",
    ],
    chips: [
      { label: "Complete", variant: "p" },
      { label: "Data-Heavy", variant: "o" },
    ],
    metrics: [
      { label: "KPI Strategy", value: "Pre-computed" },
      { label: "Charts", value: "Recharts" },
      { label: "Export", value: "CSV Stream" },
    ],
    highlights: [
      "Write-time KPI pre-computation",
      "MongoDB aggregation pipeline design",
      "Date-range filter propagation end-to-end",
      "Streamed CSV export without buffering",
    ],
    links: [
      { label: "GitHub", href: "#" },
      { label: "Live Demo", href: "#" },
    ],
    image: {
      aspect: "16/9",
      label: "Analytics Dashboard",
      hint: "1200 × 675px recommended",
      accent: 0,
    },
  },
  {
    id: "shopui",
    index: "05",
    icon: "🛒",
    status: "wip",
    type: "E-Commerce · Frontend",
    category: "Frontend",
    title: "ShopUI",
    tagline: "Pixel-precise storefront with multi-step checkout",
    description:
      "A pixel-precise e-commerce storefront built with React and Redux Toolkit. Features a multi-step checkout, cart persistence, optimistic stock updates, and full mobile responsiveness.",
    longDescription:
      "Cart persistence uses a hybrid strategy — localStorage for guest sessions merging into the authenticated cart on sign-in, handled server-side with MongoDB transactions to prevent duplication. Stock updates are optimistic at the UI layer with server-side rollback on conflict. The checkout is a multi-step wizard with per-step validation and progress saved to prevent data loss on navigation.",
    tags: [
      "React",
      "Redux Toolkit",
      "CSS Modules",
      "Paystack",
      "localStorage",
      "MongoDB Transactions",
    ],
    chips: [
      { label: "In Progress", variant: "b" },
      { label: "Frontend", variant: "y" },
    ],
    metrics: [
      { label: "Cart Strategy", value: "Hybrid" },
      { label: "Checkout", value: "Multi-Step" },
      { label: "Payment", value: "Paystack" },
    ],
    highlights: [
      "Guest-to-auth cart merge via transactions",
      "Optimistic stock UI with server rollback",
      "Multi-step checkout with per-step validation",
      "Full mobile-responsive layout system",
    ],
    links: [{ label: "GitHub", href: "#" }],
    image: {
      aspect: "16/9",
      label: "Storefront UI",
      hint: "1200 × 675px recommended",
      accent: 1,
    },
  },
  {
    id: "aurum",
    index: "06",
    icon: "💰",
    status: "complete",
    type: "UI/UX · Mobile Design",
    category: "UI/UX",
    title: "Aurum",
    tagline: "Luxury finance mobile app interface",
    description:
      "A high-end mobile finance application UI built as a standalone creative exercise. Explores premium dark-mode aesthetics, typography hierarchy, and micro-interaction patterns suited for a wealth management context.",
    longDescription:
      "Aurum is a design-first project — the constraint was building something that felt genuinely premium rather than generically 'finance-y'. The colour palette is anchored in deep charcoal and burnished gold, with typographic pairing chosen for legibility under dim-light reading conditions. Every screen was designed for thumb-zone ergonomics with gesture-first navigation patterns.",
    tags: [
      "React Native",
      "Framer Motion",
      "Typography",
      "Dark UI",
      "Design Systems",
      "Gesture Navigation",
    ],
    chips: [
      { label: "UI/UX", variant: "p" },
      { label: "Mobile", variant: "b" },
      { label: "Premium", variant: "y" },
    ],
    metrics: [
      { label: "Platform", value: "Mobile" },
      { label: "Screens", value: "12+" },
      { label: "Theme", value: "Dark/Gold" },
    ],
    highlights: [
      "Thumb-zone ergonomic layout system",
      "Custom dark palette with gold accents",
      "Gesture-first navigation architecture",
      "Premium typography pairing strategy",
    ],
    links: [
      { label: "Case Study", href: "/case-studies/aurum" },
      { label: "GitHub", href: "#" },
    ],
    image: {
      aspect: "16/9",
      label: "Mobile App Screens",
      hint: "1200 × 675px recommended",
      accent: 2,
    },
  },
];
