export const services = [
  {
    idx: "01",
    accent: "brand.accent",
    accentRgb: "232,255,71",
    icon: "⬡",
    label: "Full-Stack Development",
    tagline: "End-to-end. Nothing handed off.",
    description:
      "I take a product from blank repo to deployed system — React frontend, Express API, MongoDB data layer, third-party integrations, and everything that holds it together. You get a codebase that's readable, extensible, and won't need a full rewrite when requirements change.",
    deliverables: [
      "React SPA or multi-page frontend",
      "Node.js / Express REST API",
      "MongoDB schema + query design",
      "Auth system (JWT + httpOnly cookies)",
      "Third-party integrations (payments, email, storage)",
      "Deployment-ready build + environment config",
    ],
    tags: [
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "Redux Toolkit",
      "Socket.io",
    ],
    chip: { label: "Most Requested", variant: "y" },
    cta: "Discuss Your Project",
  },
  {
    idx: "02",
    accent: "brand.accent2",
    accentRgb: "71,200,255",
    icon: "◈",
    label: "Backend Architecture",
    tagline: "Designed to survive growth.",
    description:
      "I design and implement backends that hold up when traffic doubles, teams grow, or product scope shifts. This means thinking through data models, failure modes, API contracts, and extraction points before writing a single route handler — not patching them in six months later.",
    deliverables: [
      "Data model + schema design (Mongoose)",
      "Modular MVC project structure",
      "Middleware pipeline (validation, auth, rate-limiting)",
      "Aggregation pipeline optimisation",
      "Multi-doc transaction patterns",
      "Redis / BullMQ extraction-ready architecture",
    ],
    tags: [
      "Node.js",
      "MongoDB",
      "Zod",
      "Middleware",
      "Aggregation",
      "Transactions",
    ],
    chip: { label: "Deep Speciality", variant: "b" },
    cta: "Talk Architecture",
  },
  {
    idx: "03",
    accent: "brand.accent3",
    accentRgb: "255,107,71",
    icon: "◎",
    label: "API Design & Integration",
    tagline: "Clean contracts. Zero ghost transactions.",
    description:
      "Well-designed APIs are invisible — they just work. I design RESTful APIs with consistent contracts, cursor-based pagination for scale, HMAC-verified webhook pipelines, and centralised validation so every surface of the API behaves predictably.",
    deliverables: [
      "RESTful API design + versioning strategy",
      "Centralised Zod validation layer",
      "Paystack / Stripe webhook pipeline (HMAC)",
      "Cursor-based pagination",
      "Cloudinary + Resend integration",
      "Postman collection + API documentation",
    ],
    tags: ["REST", "Zod", "Paystack", "Webhooks", "Cloudinary", "Resend"],
    chip: { label: "Production-Proven", variant: "o" },
    cta: "Plan the Integration",
  },
  {
    idx: "04",
    accent: "brand.accent4",
    accentRgb: "180,127,255",
    icon: "◇",
    label: "Consulting & Code Review",
    tagline: "A second pair of eyes with opinions.",
    description:
      "I review existing codebases and give you an honest picture: what will break under load, where security assumptions are fragile, what refactors are worth the cost, and what can stay as-is. Delivered as a structured written report with prioritised action items — not a list of style nits.",
    deliverables: [
      "Architecture review (data model, API design, modularity)",
      "Security audit (auth, validation, webhook verification)",
      "Performance review (queries, pagination, indexes)",
      "Written report with prioritised findings",
      "1-hour walkthrough call",
      "30-day follow-up Q&A window",
    ],
    tags: [
      "Architecture",
      "Security",
      "Performance",
      "MongoDB",
      "Express",
      "React",
    ],
    chip: { label: "Fixed Scope", variant: "p" },
    cta: "Book a Review",
  },
];

export const steps = [
  {
    num: "01",
    title: "Discovery Call",
    desc: "We align on scope, timeline, constraints, and what success actually looks like.",
  },
  {
    num: "02",
    title: "Architecture Proposal",
    desc: "I map out the data model, API surface, and integration points before writing code.",
  },
  {
    num: "03",
    title: "Iterative Build",
    desc: "Weekly milestones, async updates, and early access to staging — no black-box periods.",
  },
  {
    num: "04",
    title: "Handoff & Support",
    desc: "Clean codebase, full documentation, and a 30-day window for questions after delivery.",
  },
];
